### ISSUE TITLE
Possible to release code under LGPL?

### ISSUE THREAD

**Issue by joelpresence** [adamstark/Sound-Analyser#3]
Hi Adam,

This is awesome stuff - thanks so much for releasing it!  I really enjoy reading your papers and I'm presently reading your Ph.D. dissertation as well.  :-)

I was wondering, is it possible to also release this code under the LGPL?  Unfortunately, the GPL makes it difficult to use this code in a commercial product.  We would of course give full credit and thanks to you with a link in an about screen of any commercial product we use it in.

Thanks and best wishes,

Joel

**Comment by adamstark** [comment]
Hi Joel,

Thanks for getting in touch and for your interest in my work. :)

I'm afraid my choice of license is quite deliberate - it was to significant cost to myself that I developed this plug-in (in terms of time away from paid work). I decided to not allow others to use this work in closed source commercial plug-ins for free, as this plug-in embodies many days, weeks and months of research and development time. This work wasn't publicly funded by a university, rather it was developed in my spare time over many late nights.

I understand some find the GPL frustrating and restrictive, but for me it is just a safe way of sharing my work with researchers, artists and others who want to use my work for no commercial purpose, whilst maintaining my position of needing to be paid for commercial use of my work in order to pay my rent (I wish I didn't have to do that either!).

I hope you understand! I'd definitely be interested to hear more about what you would like to use the plug-in for,

Best,

Adam

**Comment by joelpresence** [comment]
Hi Adam,

Thanks for getting back to me so quickly.  I appreciate your careful response.  Thanks for clarifying.

Your response makes sense, we all need to pay the rent!  :-) I wasn't aware that you were also commercially licensing this software.  Do you have a "rate sheet" with commercial license fees for this library?  If we did use this in our app we'd want to know how you structure fees - is it a per developer seat fee or per app download fee or certain fee based on total revenue of our company?

I think before we start experimenting with this library we want to understand the cost of commercial use before committing developer resources.

If you can point me to a link to your commercial fees please do, or we can continue this conversation offline via direct email.

Please let me know and thanks again,

Joel

**Comment by adamstark** [comment]
Hi Joel,

Yes, let's discuss further by email (you can find mine here: http://adamstark.co.uk/contact). In terms of commercial fees, I'd need to give it some thought.

Perhaps you could clarify whether you are interested in the plug-in (Sound Analyser) or the audio analysis "guts" which I have packaged as a separate library called Gist:

https://github.com/adamstark/gist

Let me know!

Thanks,

Adam

**Comment by joelpresence** [comment]
Hi Adam,

I think we'd be interested in using Gist in our commercial product: if our app was downloaded 10k times, it would be Gist that would be downloaded 10k times (in binary form, compiled into our app) alongside our app.  We would not offer Gist as a separate download of course, only compiled into our app.

For the plug-in, I think we'd be interested in using it for prototyping, but not for commercial release - it would only be used within our dev environment and not released outside our company laptops.

I don't see your email on your contact page, only your Twitter handle.  My email is joel at presence dash labs dot com.  Could you email me there or give me your email address and I'll email you?

Thanks!

Joel

**Comment by adamstark** [comment]
Hi Joel,

Try...

hello [at] adamstark [dot] co [dot] uk

Thanks!

Adam

**Comment by joelpresence** [comment]
Email sent ...
